version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Compilando la aplicación...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
